import path from "node:path"

const root = process.cwd()
const sourcePath = path.join(root, "specs/xocp/documentacao.md")
const outputPath = path.join(root, "packages/app/src/generated/documentacao.ts")
const source = await Bun.file(sourcePath).text()
const output = `// Generated by script/generate-xocp-docs.ts — do not edit manually.
// Source: specs/xocp/documentacao.md

export const documentacaoMarkdown = ${JSON.stringify(source)}
`

if (process.argv.includes("--check")) {
  const existing = await Bun.file(outputPath).text().catch(() => "")
  if (existing !== output) {
    console.error("XOCP docs are out of date. Run: bun run generate:xocp-docs")
    process.exit(1)
  }
  console.log("XOCP docs are up to date")
} else {
  await Bun.write(outputPath, output)
  console.log("Generated packages/app/src/generated/documentacao.ts")
}
